import MidnightExpress.Validation

/- Generated by publish.py from verified installed bundle bytes and lock.json.
   Pins the modeled release; does not prove bundle loading or wire decoding. -/
namespace MidnightExpress.ProfilePins

example : Profile.rfq.name = "rfq.v0.2" := rfl
example : Profile.rfq.eventType = "mpe.rfq.quote.v0.2" := rfl
example : Profile.rfq.dataSchema = "urn:mpe:model:rfq.v0.2" := rfl
example : Profile.rfq.contract = "sha256:8b5c6b89f6019fcb06b479e92f1b3bea340ac500cc218341e368e1ed2093071c" := rfl
example : Profile.rfq.role = .dealer := rfl
example (e : Envelope) (h : e.Matches .rfq) : e.specversion = "1.0" := by
  rcases h with ⟨hSpec, hContent, hType, hSchema, hProfile, hContract⟩
  assumption
example (e : Envelope) (h : e.Matches .rfq) : e.contentType = "application/json" := by
  rcases h with ⟨hSpec, hContent, hType, hSchema, hProfile, hContract⟩
  assumption
example : Profile.invoice.name = "invoice.v0.2" := rfl
example : Profile.invoice.eventType = "mpe.invoice.payment-observed.v0.2" := rfl
example : Profile.invoice.dataSchema = "urn:mpe:model:invoice.v0.2" := rfl
example : Profile.invoice.contract = "sha256:dd3b68c4f25c4ca87a57e5e5dda88cb8a1630fa9a1b0ab394744fdf984eb047a" := rfl
example : Profile.invoice.role = .paymentAdapter := rfl
example (e : Envelope) (h : e.Matches .invoice) : e.specversion = "1.0" := by
  rcases h with ⟨hSpec, hContent, hType, hSchema, hProfile, hContract⟩
  assumption
example (e : Envelope) (h : e.Matches .invoice) : e.contentType = "application/json" := by
  rcases h with ⟨hSpec, hContent, hType, hSchema, hProfile, hContract⟩
  assumption
example : Profile.agent.name = "agent.v0.2" := rfl
example : Profile.agent.eventType = "mpe.agent.approval.v0.2" := rfl
example : Profile.agent.dataSchema = "urn:mpe:model:agent.v0.2" := rfl
example : Profile.agent.contract = "sha256:beaf501a8fdeefe757c340b1945dcd3e9c7c6e3fb4e00612f724afab7605b330" := rfl
example : Profile.agent.role = .humanApprover := rfl
example (e : Envelope) (h : e.Matches .agent) : e.specversion = "1.0" := by
  rcases h with ⟨hSpec, hContent, hType, hSchema, hProfile, hContract⟩
  assumption
example (e : Envelope) (h : e.Matches .agent) : e.contentType = "application/json" := by
  rcases h with ⟨hSpec, hContent, hType, hSchema, hProfile, hContract⟩
  assumption
example : maxCoefficient = 999999999999999999 := rfl

example : decodeCurrency "iso4217:USD" = some .usd := by decide
example : decodeUnit "Share" = some .share := by decide
example : decodeUnit "Step" = some .step := by decide
example : decodeOperation "WriteReport" = some .writeReport := by decide
example (c : Context) (e : Envelope) (q : RFQ) (h : rfqCheck c e q = true) :
    q.price.baseQuantity = 1 := by
  have valid := (rfqCheck_iff c e q).mp h
  cases valid
  simp_all [Decimal.ValidAt]

example (c : Context) (e : Envelope) (q : RFQ) (h : rfqCheck c e q = true) :
    q.terms.quantity.value.scale = 0 := by
  have valid := (rfqCheck_iff c e q).mp h
  cases valid
  simp_all [Decimal.ValidAt]

example (c : Context) (e : Envelope) (q : RFQ) (h : rfqCheck c e q = true) :
    q.price.value.scale = 2 := by
  have valid := (rfqCheck_iff c e q).mp h
  cases valid
  simp_all [Decimal.ValidAt]

example (c : Context) (e : Envelope) (q : RFQ) (h : rfqCheck c e q = true) :
    q.cash.scale = 2 := by
  have valid := (rfqCheck_iff c e q).mp h
  cases valid
  simp_all [Decimal.ValidAt]

example (c : Context) (e : Envelope) (i : Invoice) (h : invoiceCheck c e i = true) :
    i.rail = "fixture-bank-v1" := by
  have valid := (invoiceCheck_iff c e i).mp h
  cases valid
  simp_all [Decimal.ValidAt]

example (c : Context) (e : Envelope) (i : Invoice) (h : invoiceCheck c e i = true) :
    i.amount.scale = 2 := by
  have valid := (invoiceCheck_iff c e i).mp h
  cases valid
  simp_all [Decimal.ValidAt]

example (c : Context) (e : Envelope) (i : Invoice) (h : invoiceCheck c e i = true) :
    i.terms.payable.scale = 2 := by
  have valid := (invoiceCheck_iff c e i).mp h
  cases valid
  simp_all [Decimal.ValidAt]

example (c : Context) (e : Envelope) (a : Approval) (h : approvalCheck c e a = true) :
    a.authorityDomain = "urn:mpe:sandbox:local" := by
  have valid := (approvalCheck_iff c e a).mp h
  cases valid
  simp_all [Decimal.ValidAt]

example (c : Context) (e : Envelope) (a : Approval) (h : approvalCheck c e a = true) :
    a.budgetWindow = "window:fixture" := by
  have valid := (approvalCheck_iff c e a).mp h
  cases valid
  simp_all [Decimal.ValidAt]

example (c : Context) (e : Envelope) (a : Approval) (h : approvalCheck c e a = true) :
    a.maxEffects = 1 := by
  have valid := (approvalCheck_iff c e a).mp h
  cases valid
  simp_all [Decimal.ValidAt]

example (c : Context) (e : Envelope) (a : Approval) (h : approvalCheck c e a = true) :
    a.proposal.budget.value.scale = 0 := by
  have valid := (approvalCheck_iff c e a).mp h
  cases valid
  simp_all [Decimal.ValidAt]

end MidnightExpress.ProfilePins
