'use strict';
const components={
sdk:{title:'An SDK for business events',label:'APPLICATION / CUSTOM SDK',body:'The proposed SDK gives humans, wallets, DApps and agents a private local watch over supported business events. A Rust core and TypeScript-facing interface would expose bounded reads, pause, recovery and review checkpoints through a durable consumer journal.',connection:'Application adapters map source identity, version, finality and snapshot/delta state → signed business intent → MPE envelope. CloudEvents-compatible identity, source, type and schema stay inside encryption; AsyncAPI documents operations.',gate:'Implement principal-bound grants, immutable watch revisions, bounded delivery and durable checkpoints. Keep consumer pressure local so it cannot reveal matching events through network timing. Versioned agent adapters read the same journal; notifications and wallet connections grant no action authority. The browser dashboard demonstrates interactions over mock data.',href:'subscriptions.html',link:'Explore local subscriptions',related:['seal','recovery']},
seal:{title:'Sealing and local recognition',label:'WIRE / ORIGINAL MPE PROFILE',body:'The MPE wire design puts authenticated encrypted payloads and signatures in fixed-size envelope classes. Receivers would recognize relevant envelopes with local keys and salted tags; relays would carry the opaque envelopes.',connection:'Signed intent → sealed envelope → RLN admission → GossipSub. OpenMLS can protect session content inside this composition.',gate:'Semantic metadata is encrypted; salt, nonce and recognition tag are readable prefix fields. The symmetric launch profile does not claim forward secrecy, ingress anonymity or global timing protection.',href:'https://github.com/CharlesHoskinson/midnight-express/blob/main/docs/product-requirements/requirements-fit-and-open-source.md',link:'Read the MPE design',related:['sdk','membership','gossip','groups']},
membership:{title:'Publication membership and quotas',label:'MEMBERSHIP / ONE RLN-STYLE PROOF',body:'Semaphore-derived patterns support independent admission identities, commitments and witness updates. Finalized Midnight Registry roots remain authoritative. Zerokit is the preferred RLN evaluation engine.',connection:'Membership lifecycle → finalized Registry root → one content-bound membership-and-quota proof → GossipSub validation. No second Semaphore proof is added per event.',gate:'Exact hash, field, commitment and tree compatibility must be established. Quota scope excludes envelope ID and current root to prevent resets. Conflicting credit reuse can expose an admission secret for revocation; this is not a globally serialized pre-send cap. Bus nodes durably distinguish duplicates from conflicting credit shares. Finalized snapshots and bounded old-root grace govern eligibility. The targets are an admission slot ≤ 4096 bytes and verification ≤ 10 ms on the specified VM; they remain unmeasured. Adapt and measure the proof relation before acceptance.',href:'https://github.com/vacp2p/zerokit',link:'Explore Zerokit',related:['seal','gossip']},
gossip:{title:'Distribution without business topics',label:'TRANSPORT / RUST-LIBP2P GOSSIPSUB',body:'The proposed Rust GossipSub sidecar would distribute sealed events alongside Midnight nodes. Receivers take traffic for an entire shard and identify relevant messages locally, keeping business subscriptions away from delivery operators. Connections, shard participation, timing and size can remain observable.',connection:'Admitted envelopes fan out to receivers, retained stores and the anchor branch. Receivers decide relevance locally; the network does not route on private event semantics.',gate:'Use the selected anonymous-message profile and finish expiry checks for cached, queued and requested sends. Peer scoring and transport encryption alone do not establish private reception.',href:'https://github.com/libp2p/rust-libp2p',link:'Explore rust-libp2p',related:['membership','store','recovery','anchor']},
store:{title:'Recover the missing envelopes',label:'RETENTION / CUSTOM MPE PROTOCOL',body:'The custom store protocol would replicate opaque envelopes for the baseline 48-hour retention window. Receivers could retrieve that window using cursors, with explicit gaps where history is unavailable.',connection:'GossipSub → replicated opaque retention → whole-shard backfill → local recognition. Signed persistence receipts are issued only after durable persistence.',gate:'Database selection does not implement replication, receipts or retention. Long-lived archives need separate key, funding and history policies. Store operators do not inherit endpoint plaintext or keys.',href:'https://github.com/CharlesHoskinson/midnight-express/blob/main/docs/product-requirements/requirements-fit-and-open-source.md',link:'Read the store requirements',related:['gossip','recovery']},
recovery:{title:'Durable progress in the endpoint',label:'RECOVERY / UMBRADB + POSTGRESQL',body:'Use Midnight-aware UmbraDB in trusted Node backend workflow hosts. SQLite is the standalone Rust/client option. Both sit inside the endpoint trust domain.',connection:'Local recognition → durable inbox → authenticated policy → proposed atomic processing of local effect, deduplication, outbox, checkpoint and cursor. External destinations require idempotency or reconciliation.',gate:'Umbra saveAndAdvance covers checkpoint and cursor. A local public-API composition has passed report-row recovery tests on PostgreSQL. Full MPE processing, strict durability, lease ownership and protected restore still require integration against the future-release requirements. Shared schemas are not tenant isolation; keys and at-rest protection need explicit design.',href:'https://github.com/CharlesHoskinson/UmbraDB/pull/5',link:'Read the Umbra proposal',related:['store','sdk','authority']},
groups:{title:'Optional group session security',label:'SESSION / OPTIONAL OPENMLS EXTENSION',body:'OpenMLS is the selected group-oriented security extension, including a two-member profile. It would protect session payloads inside MPE after integration. The launch pilot would retain the original symmetric profile.',connection:'Application role/device identity → group credentials and epoch state → protected payload → MPE envelope. Removal and rekeying restrict access to future epochs.',gate:'Validate hidden group metadata, identity binding, commit ordering, wire fit, crash recovery and erasure. Removal does not delete past plaintext. Signal remains a deferred pairwise alternative outside the default stack.',href:'https://github.com/openmls/openmls',link:'Explore OpenMLS',related:['seal','recovery']},
anchor:{title:'Batch window commitments',label:'LEDGER / CUSTOM MIDNIGHT ANCHOR',body:'The proposed anchor records batch commitments to envelope identities on Midnight. Ordinary coordination would not require a ledger transaction for every event.',connection:'Distribution → anchor window → finalized inclusion evidence. For a contract effect, that evidence joins signed authority and replay/message-binding proofs.',gate:'Inclusion establishes membership in a committed window. It does not prove availability, delivery, business authorization or completion. Anchor processing runs in parallel with retention and reception.',href:'https://github.com/CharlesHoskinson/midnight-express/blob/main/docs/product-requirements/requirements-fit-and-open-source.md',link:'Read the ledger requirements',related:['gossip','authority']},
authority:{title:'Proof before a contract effect',label:'AUTHORIZATION / CUSTOM CONSUMER',body:'Before committing an effect, a consuming contract would verify the signed instruction and its authority, check its binding to the anchored sealed message, and enforce atomic replay protection.',connection:'Authenticated application workflow + finalized anchor evidence → consumer proof → atomic contract effect. An explicit signed business acknowledgement is a separate application event.',gate:'Complete CON-043 signed authority, CON-044 replay nullifiers and CON-060 anchored-message binding. Contract-origin events also require exact carried bytes and applied-phase/finality checks.',href:'https://github.com/CharlesHoskinson/midnight-express/blob/main/docs/product-requirements/requirements-fit-and-open-source.md',link:'Read the authority requirements',related:['recovery','anchor','sdk']}
};
const panel=document.querySelector('#component-detail');
function selectComponent(key){const c=components[key];document.querySelectorAll('[data-component]').forEach(b=>{b.classList.toggle('selected',b.dataset.component===key);b.classList.toggle('related',c.related.includes(b.dataset.component));b.setAttribute('aria-pressed',String(b.dataset.component===key));});panel.replaceChildren();panel.innerHTML=`<span class="detail-label">${c.label}</span><h3>${c.title}</h3><p>${c.body}</p><h4>How it connects</h4><p>${c.connection}</p><div class="gate"><h4>Work required before integration acceptance</h4><p>${c.gate}</p></div><a href="${c.href}">${c.link}</a>`;}
document.querySelectorAll('[data-component]').forEach(b=>b.addEventListener('click',()=>selectComponent(b.dataset.component)));selectComponent('gossip');
const journey=[
['Define the intent','Application → SDK','Create a typed event and sign the business intent.','Private event schemas carry identity, source, type and correlation. Application policy sets roles, allowed actions and expiry. Source authentication and permission to act remain separate.','Event semantics belong inside encryption.','sdk'],
['Seal the envelope','SDK → MPE envelope','Prepare an authenticated sealed event.','Fixed-size classes, encryption and signatures preserve the selected wire profile. Salted keyed tags allow endpoint-local recognition. Optional OpenMLS protects session content inside this envelope.','The launch symmetric profile makes no forward-secrecy claim.','seal'],
['Prove admission','Registry → one RLN proof','Prove membership and allowance together.','One proposed RLN-style relation binds finalized membership, per-class credits and abuse evidence to the envelope. Semaphore-derived lifecycle patterns support witness maintenance.','Publication admission does not establish business authority.','membership'],
['Distribute','Admission → GossipSub','Relay opaque events across the overlay.','Whole-shard distribution avoids business topics and content-aware selectors. Expiry applies to every send path, including caches and queues.','Retention, reception and anchoring now proceed in parallel.','gossip'],
['Retain and recover','Overlay → stores → receiver','Persist envelopes and backfill gaps.','The custom store protocol replicates opaque envelopes, issues signed receipts after persistence and supplies whole-window backfill. The database is only one part of this behavior.','A persistence receipt does not establish delivery or acceptance.','store'],
['Recognize locally','Whole shard → local inbox','Recognize and open relevant events at the endpoint.','The receiver uses local keyed matching and authenticates relevant content. Recognition must not trigger upstream selectors, automatic acknowledgements, push or attachment retrieval.','Private mobile discovery and retrieval remain separate research work.','seal'],
['Commit local processing','Inbox → policy → durable commit','Record recoverable workflow progress.','The proposed atomic composition commits local effects, deduplication, outbox, checkpoint and cursor together. A local sandbox exercises this with a report-row effect. UmbraDB/PostgreSQL serves trusted Node hosts; SQLite serves standalone Rust clients.','External effects need destination idempotency or reconciliation.','recovery'],
['Establish ledger evidence','Parallel anchor → optional consumer proof','Anchor inclusion supports an optional contract path.','Finalized window inclusion is independent of local coordination. A requested contract effect additionally requires signed authority, replay protection and anchored-message binding.','Many notifications complete without a contract effect.','anchor'],
['Acknowledge the outcome','Application policy → new signed event','Explicitly state the business result.','When the workflow requires it, an authorized endpoint signs the application-defined outcome and publishes it through the same sealing and admission path. Receipt alone never means an offer was accepted or a payment posted.','Acknowledgement is explicit business policy, never automatic recognition feedback.','authority']
];
const steps=document.querySelector('#journey-steps');journey.forEach((s,i)=>{const b=document.createElement('button');b.type='button';b.setAttribute('aria-controls','journey-detail');b.textContent=s[0];b.addEventListener('click',()=>selectStep(i));steps.append(b);});function selectStep(i){const s=journey[i];[...steps.children].forEach((b,k)=>{b.classList.toggle('active',k===i);b.setAttribute('aria-pressed',String(k===i));});document.querySelector('#journey-detail').innerHTML=`<span class="detail-label">${s[1]}</span><h3>${s[2]}</h3><p>${s[3]}</p><p class="scope">${s[4]}</p><button class="component-link" type="button">Explore this component</button>`;document.querySelector('.component-link').addEventListener('click',()=>{selectComponent(s[5]);document.querySelector('#architecture').scrollIntoView();document.querySelector('[data-component="'+s[5]+'"]').focus({preventScroll:true});});}selectStep(0);

const workflowPanel=document.querySelector('#workflow-panel');
function showWorkflow(key){
 const w=window.MPE_PRODUCT.workflows[key];
 document.querySelectorAll('[data-workflow]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.workflow===key)));
 const esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 workflowPanel.innerHTML=`<span class="detail-label">${esc(w.label)}</span><h3>${esc(w.title)}</h3><p class="workflow-context">${esc(w.context)}</p><p class="workflow-people"><strong>Who is involved:</strong> ${esc(w.who)}</p><ol class="workflow-story">${w.steps.map(step=>`<li><strong>${esc(step[0])}</strong><p>${esc(step[1])}</p></li>`).join('')}</ol><div class="workflow-outcome"><div><h4>Value to test</h4><p>${esc(w.value)}</p><h4>Measure in the pilot</h4><p>${esc(w.measure)}</p></div><div><h4>Initial scope</h4><p>${esc(w.scope)}</p><a class="workflow-architecture" href="#architecture">See what supports this workflow</a></div></div>`;
}
document.querySelectorAll('[data-workflow]').forEach(b=>b.addEventListener('click',()=>showWorkflow(b.dataset.workflow)));
showWorkflow('quotes');
