//! Independent RFQ interpreter and cents-per-lot adapter. No calls to Python/TypeScript.
use serde::{de::{self,MapAccess,SeqAccess,Visitor},Deserialize,Deserializer};
use serde_json::{Value,json};use sha2::{Digest,Sha256};use std::{collections::BTreeMap,fmt,fs,io::{self,BufRead},path::Path};
struct Strict(Value);
impl<'de> Deserialize<'de> for Strict{fn deserialize<D:Deserializer<'de>>(d:D)->Result<Self,D::Error>{struct V;impl<'de> Visitor<'de> for V{type Value=Strict;fn expecting(&self,f:&mut fmt::Formatter)->fmt::Result{write!(f,"strict integer JSON")}
 fn visit_bool<E:de::Error>(self,v:bool)->Result<Strict,E>{Ok(Strict(json!(v)))}fn visit_unit<E:de::Error>(self)->Result<Strict,E>{Ok(Strict(Value::Null))}
 fn visit_u64<E:de::Error>(self,v:u64)->Result<Strict,E>{if v>9007199254740991{return Err(E::custom("integer range"))}Ok(Strict(json!(v)))}
 fn visit_i64<E:de::Error>(self,_:i64)->Result<Strict,E>{Err(E::custom("signed token"))}fn visit_f64<E:de::Error>(self,_:f64)->Result<Strict,E>{Err(E::custom("floating token"))}
 fn visit_str<E:de::Error>(self,v:&str)->Result<Strict,E>{if v.chars().count()>512{return Err(E::custom("string bound"))}Ok(Strict(json!(v)))}
 fn visit_string<E:de::Error>(self,v:String)->Result<Strict,E>{self.visit_str(&v)}
 fn visit_seq<A:SeqAccess<'de>>(self,mut a:A)->Result<Strict,A::Error>{let mut v=vec![];while let Some(x)=a.next_element::<Strict>()?{v.push(x.0);if v.len()>16{return Err(de::Error::custom("array bound"))}}Ok(Strict(json!(v)))}
 fn visit_map<A:MapAccess<'de>>(self,mut a:A)->Result<Strict,A::Error>{let mut m=BTreeMap::new();while let Some(k)=a.next_key::<String>()?{if k.chars().count()>512||m.contains_key(&k){return Err(de::Error::custom("duplicate key"))}m.insert(k,a.next_value::<Strict>()?.0);}Ok(Strict(json!(m)))}
}d.deserialize_any(V)}}
type R<T>=Result<T,String>;
fn text<'a>(v:&'a Value)->R<&'a str>{v.as_str().ok_or("string".into())}
fn depth(v:&Value,n:usize)->R<()>{if n>12{return Err("depth".into())}match v{Value::Object(m)=>for x in m.values(){depth(x,n+1)?},Value::Array(a)=>for x in a{depth(x,n+1)?},_=>{}}Ok(())}
fn parse(raw:&str)->R<Value>{if raw.len()>3926{return Err("body bound".into())}let v=serde_json::from_str::<Strict>(raw).map_err(|e|e.to_string())?.0;depth(&v,0)?;Ok(v)}
fn canon(v:&Value)->String{match v{Value::Object(m)=>{let mut keys:Vec<_>=m.keys().collect();keys.sort_by(|a,b|a.encode_utf16().cmp(b.encode_utf16()));format!("{{{}}}",keys.iter().map(|k|format!("{}:{}",serde_json::to_string(k).unwrap(),canon(&m[*k]))).collect::<Vec<_>>().join(","))},Value::Array(a)=>format!("[{}]",a.iter().map(canon).collect::<Vec<_>>().join(",")),_=>serde_json::to_string(v).unwrap()}}
fn hash(raw:&[u8])->String{format!("sha256:{:x}",Sha256::digest(raw))}
fn exact(pattern:&str,s:&str)->R<()>{let p=pattern.strip_suffix("(?![\\s\\S])").unwrap_or(pattern);let re=regex::Regex::new(p).map_err(|e|e.to_string())?;if !re.find(s).is_some_and(|m|m.start()==0&&m.end()==s.len()){return Err("grammar".into())}Ok(())}
fn schema(s:&Value,v:&Value)->R<()>{if let Some(c)=s.get("const"){if c!=v{return Err("const".into())}}if let Some(a)=s["enum"].as_array(){if !a.contains(v){return Err("enum".into())}}
 if s["type"]=="object"{let m=v.as_object().ok_or("object")?;for k in s["required"].as_array().ok_or("required")?{if !m.contains_key(text(k)?){return Err("missing".into())}}for(k,x)in m{let child=s["properties"].get(k).ok_or("unknown")?;schema(child,x)?}}
 if s["type"]=="string"{let x=text(v)?;if s["maxLength"].as_u64().is_some_and(|n|x.chars().count()>n as usize){return Err("length".into())}if let Some(p)=s["pattern"].as_str(){exact(p,x)?}}
 Ok(())}
fn no_refs(v:&Value)->R<()>{if let Some(m)=v.as_object(){for(k,x)in m{if ["$ref","$dynamicRef","$recursiveRef"].contains(&k.as_str()){return Err("refs".into())}no_refs(x)?}}else if let Some(a)=v.as_array(){for x in a{no_refs(x)?}}Ok(())}
fn read(p:&Path)->R<Vec<u8>>{if fs::symlink_metadata(p).map_err(|e|e.to_string())?.file_type().is_symlink(){return Err("symlink".into())}fs::read(p).map_err(|e|e.to_string())}
fn load(root:&Path,e:&Value)->R<Value>{let contract=text(&e["mpecontract"])?;exact("^sha256:[0-9a-f]{64}",contract)?;if e["mpeprofile"]!="rfq.v0.2"{return Err("unsupported".into())}let installed:Value=serde_json::from_slice(&read(&root.join("profiles/installed.json"))?).map_err(|e|e.to_string())?;let entry=&installed[contract];let directory=format!("bundles/{}",&contract[7..]);if entry["mode"]!="conformance"||entry["profile"]!=e["mpeprofile"]||entry["directory"]!=directory{return Err("installed".into())}let folder=root.join(&directory);if root.join("bundles").symlink_metadata().map_err(|e|e.to_string())?.file_type().is_symlink(){return Err("bundle ancestor symlink".into())}if fs::symlink_metadata(&folder).map_err(|e|e.to_string())?.file_type().is_symlink(){return Err("symlink".into())}let m:Value=serde_json::from_slice(&read(&folder.join("manifest.json"))?).map_err(|e|e.to_string())?;if hash(canon(&m).as_bytes())!=contract||m["profile"]!=e["mpeprofile"]||m.as_object().map_or(0,|o|o.len())!=8||m["bundleVersion"]!=1||m["version"]!="0.2"||m["status"]!="experimental-model-only"||m["signatures"]!="unsigned-fixture-only"{return Err("manifest".into())}
 let resources=m["resources"].as_object().ok_or("resources")?;if resources.len()!=3||!["schema.json","rules.json","core.json"].iter().all(|k|resources.contains_key(*k)){return Err("closure".into())}let mut captured=BTreeMap::new();for(k,h)in resources{let raw=read(&folder.join(k))?;if hash(&raw)!=text(h)?{return Err("integrity".into())}captured.insert(k,serde_json::from_slice::<Value>(&raw).map_err(|e|e.to_string())?);}let schema=captured.get(&"schema.json".to_string()).ok_or("schema")?.clone();no_refs(&schema)?;if captured[&"rules.json".to_string()]["profile"]!=e["mpeprofile"]||captured[&"rules.json".to_string()]["role"]!=m["role"]||captured[&"core.json".to_string()]["version"]!="0.2"||schema["$id"]!=format!("urn:mpe:model:{}",text(&e["mpeprofile"])?){return Err("metadata".into())}Ok(schema)}
fn time(v:&Value)->R<i64>{let s=text(v)?;exact("^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\\.000Z",s)?;if s.starts_with("0000")||&s[17..19]=="60"{return Err("year".into())}let t=chrono::DateTime::parse_from_rfc3339(s).map_err(|e|e.to_string())?;if t.format("%Y-%m-%dT%H:%M:%S.000Z").to_string()!=s{return Err("calendar".into())}Ok(t.timestamp())}
fn num(v:&Value)->R<u128>{text(v)?.parse::<u128>().map_err(|e|e.to_string())}
fn interpret(root:&Path,raw:&str,c:&Value)->R<Value>{let e=parse(raw)?;schema(&load(root,&e)?,&e)?;if c["fixtureTrust"]!="trusted-test-fixture-only"{return Err("trust".into())}let d=&e["data"];let source=&c["sources"][text(&e["source"])?];let r=&c["rfqs"][text(&d["rfqId"])?];if source["role"]!="dealer"||source["principal"]!=d["dealer"]||r["state"]!="open"{return Err("source state".into())}for k in ["requester","dealer","requesterSide","asset","quantity","currency"]{if d[k]!=r[k]{return Err("terms".into())}}
 let(buyer,seller)=if d["requesterSide"]=="BuyAsset"{(&d["requester"],&d["dealer"])}else{(&d["dealer"],&d["requester"])};if buyer==seller||&d["buyer"]!=buyer||&d["seller"]!=seller{return Err("roles".into())}if d["price"]["assetRef"]!=d["asset"]||d["price"]["unit"]!=d["quantity"]["unit"]||d["price"]["currency"]!=d["currency"]{return Err("basis".into())}let now=time(&c["now"])?;if !(time(&e["time"])?<=time(&d["validFrom"])?&&time(&d["validFrom"])?<=now&&now<time(&d["validUntil"])?){return Err("expiry".into())}let cash=num(&d["quantity"]["coefficient"])?*num(&d["price"]["value"]["coefficient"])?;if cash>999999999999999999||cash!=num(&d["cash"]["coefficient"])?{return Err("cash".into())}let intent=json!({"domain":"mpe.model.intent.v0.2","source":e["source"],"type":e["type"],"profile":e["mpeprofile"],"contract":e["mpecontract"],"data":d});Ok(json!({"status":"offchain-quote-valid","businessDigest":hash(canon(&intent).as_bytes()),"canonicalEvent":canon(&e),"canonicalIntent":canon(&intent),"executes":false}))}
fn adapt_b(i:&Value,t:&Value)->R<Value>{let required=["format","quantity","quotePriceMinor","currency","basisShares","perspective","fees"];let m=i.as_object().ok_or("adapter object")?;if m.len()!=required.len()||!required.iter().all(|k|m.contains_key(*k))||i["format"]!="dealer-b.cents-lot.v1"||i["currency"]!="USD"||i["basisShares"]!="100"||i["perspective"]!="DealerSell"||i["fees"]!="None"{return Err("adapter contract".into())}exact("^[1-9][0-9]{0,17}",text(&i["quantity"])?)?;exact("^[1-9][0-9]{0,19}",text(&i["quotePriceMinor"])?)?;let cents=num(&i["quotePriceMinor"])?;if cents%100!=0||cents/100==0||cents/100>999999999999999999{return Err("division".into())}let price=cents/100;let cash=num(&i["quantity"])?*price;if cash>999999999999999999{return Err("overflow".into())}let mut e=t.clone();e["data"]["quantity"]["coefficient"]=i["quantity"].clone();e["data"]["price"]["value"]["coefficient"]=json!(price.to_string());e["data"]["cash"]["coefficient"]=json!(cash.to_string());Ok(json!({"event":e,"executes":false}))}
fn main(){let root=std::env::args().nth(1).unwrap_or("model".into());let mut occurrences:BTreeMap<String,String>=BTreeMap::new();for line in io::stdin().lock().lines(){let result=(||{let line=line.map_err(|e|e.to_string())?;if line.len()>65536{return Err("request bound".into())}let q:Value=serde_json::from_str(&line).map_err(|e|e.to_string())?;if q["kind"]=="adapter-b"{adapt_b(&q["input"],&q["template"])}else{let raw=text(&q["raw"])?;let mut result=interpret(Path::new(&root),raw,&q["context"])?;if q["kind"]=="process"{let e=parse(raw)?;let key=format!("{}|{}",text(&e["source"])?,text(&e["id"])?);let canon=text(&result["canonicalEvent"])? .to_string();if let Some(old)=occurrences.get(&key){if old!=&canon{return Err("event conflict".into())}result["status"]=json!("duplicate-event");}occurrences.insert(key,canon);}Ok(result)}})();println!("{}",result.unwrap_or(json!({"status":"reject","executes":false})));}}
