'use strict';
const assert=require('node:assert/strict');
const http=require('node:http');
const fs=require('node:fs/promises');
const path=require('node:path');
let playwright;
try { playwright=require('playwright'); } catch { playwright=require('/home/hoskinson/.local/share/mise/installs/npm-playwright/1.63.0/node_modules/playwright'); }
const dist=path.resolve(__dirname,'../dist');
(async()=>{
 const server=http.createServer(async(req,res)=>{try{const name=new URL(req.url,'http://localhost').pathname.slice(1);assert.ok(/^[a-z0-9.-]+$/.test(name));const body=await fs.readFile(path.join(dist,name));res.setHeader('Content-Type',name.endsWith('.json')?'application/json':name.endsWith('.js')?'text/javascript':name.endsWith('.css')?'text/css':'text/html');res.end(body);}catch{res.statusCode=404;res.end();}});
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));let browser;
 try{
  const executablePath=process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE||'/home/hoskinson/.cache/ms-playwright/chromium-1243/chrome-linux64/chrome';
  browser=await playwright.chromium.launch({headless:true,...(await fs.access(executablePath).then(()=>true,()=>false)?{executablePath}:{})});
  const page=await browser.newPage();const errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));
  await page.addInitScript(()=>{globalThis.__walletCalls={connect:0,status:0};globalThis.midnight={moth:{rdns:'io.shielded.moth',apiVersion:'4.0.1',connect:async networkId=>{__walletCalls.connect++;return {getConnectionStatus:async()=>{__walletCalls.status++;return {status:'connected',networkId};}};}}};});
  await page.goto(`http://127.0.0.1:${server.address().port}/subscriptions.html`);
  await page.locator('#streams .stream').first().waitFor();
  assert.equal(await page.locator('#connect').isDisabled(),true);assert.deepEqual(await page.evaluate(()=>__walletCalls),{connect:0,status:0},'Loading page must not call wallet RPC');await page.locator('#discover').click();assert.deepEqual(await page.evaluate(()=>__walletCalls),{connect:0,status:0});await page.locator('#wallet-ack').check();assert.equal(await page.locator('#connect').isDisabled(),false);await page.locator('#connect').click();await page.waitForFunction(()=>__walletCalls.status===1);assert.deepEqual(await page.evaluate(()=>__walletCalls),{connect:1,status:1});await page.locator('#check-wallet').click();await page.waitForFunction(()=>__walletCalls.status===2);await page.locator('#disconnect').click();assert.match(await page.locator('#wallet-status').textContent(),/cannot revoke/);await page.locator('#wallet-ack').uncheck();assert.equal(await page.locator('#connect').isDisabled(),true);
  const sub=cat=>page.getByRole('button',{name:`Subscribe to ${cat}`,exact:true}).first().click();
  const click=id=>page.locator(`#${id}`).click();
  const text=()=>page.locator('#subscriptions').textContent();
  const state=async()=>{const downloadPromise=page.waitForEvent('download');await click('export');const download=await downloadPromise;return JSON.parse(await fs.readFile(await download.path(),'utf8'));};
  await sub('contracts');const requestCount=requests.length;await click('tick');assert.equal(requests.length,requestCount,'Subscribing/intake must not contact a server');await click('process');assert.match(await page.locator('#inbox').textContent(),/reviewed locally; no effect executed/);
  await click('revoke');await page.locator('#subscriptions').getByRole('button',{name:'Pause',exact:true}).click();assert.match(await text(),/contracts · revoked/);await page.locator('#subscriptions select').selectOption('ops');await page.getByRole('button',{name:'Save scope revision'}).click();assert.match(await text(),/contracts · revoked/);await click('gap');assert.match(await text(),/contracts · revoked/);
  await click('reset');await sub('contracts');await click('stale');await page.getByRole('button',{name:'Pause',exact:true}).click();assert.match(await text(),/contracts · expired/);
  await click('reset');await sub('contracts');await sub('ops');const first=page.locator('.subscription').first();await first.locator('select').selectOption('ops');await first.getByRole('button',{name:'Save scope revision'}).click();assert.match(await page.locator('#announcement').textContent(),/already has a subscription/);assert.match(await first.textContent(),/contracts/);
  await click('reset');await sub('contracts');for(let i=0;i<7;i++)await click('tick');assert.match(await text(),/contracts · gapped/);assert.match(await text(),/oldest retained cursor:demo\/000001/);await page.getByRole('button',{name:'Accept gap; start after latest'}).click();assert.match(await page.locator('#announcement').textContent(),/Decide all queued/);await page.getByRole('button',{name:'Save scope revision'}).click();assert.match(await page.locator('#announcement').textContent(),/Scope edit blocked/);
  await click('process');await page.getByRole('button',{name:'Recover retained originals'}).click();assert.match(await text(),/contracts · active/);for(let i=0;i<6;i++)await click('process');const recovered=await state();assert.equal(recovered.runtime[0].processedCursor,7,'Recovery must decide every retained occurrence');assert.equal(recovered.receiptDispositions.length,7);
  await page.getByRole('button',{name:'Pause',exact:true}).click();await click('tick');const paused=await state();assert.equal(paused.runtime[0].deliveredCursor,7);await page.getByRole('button',{name:'Resume',exact:true}).click();await click('process');assert.equal((await state()).runtime[0].processedCursor,8);
  await click('gap');await page.getByRole('button',{name:'Recover retained originals'}).click();assert.match(await page.locator('#announcement').textContent(),/range unavailable/);await page.getByRole('button',{name:'Accept gap; start after latest'}).click();const accepted=await state();assert.deepEqual(accepted.intents[0].start,{mode:'after',cursor:'cursor:demo/000008'});assert.equal(accepted.intents[0].requestedState,'active');assert.ok(accepted.intentHistory.length);
  await page.locator('.subscription select').selectOption('credentials');await page.getByRole('button',{name:'Save scope revision'}).click();await click('tick');await click('process');const edited=await state();assert.equal(edited.intents[0].selector.category,'credentials');assert.equal(edited.runtime[0].processedCursor,9,'New scope checkpoint must start after its revision boundary');
  await click('reset');await sub('contracts');await page.getByRole('button',{name:'Pause',exact:true}).click();for(let i=0;i<5;i++)await click('tick');assert.match(await text(),/contracts · gapped/);const beforePausedRecovery=await state();assert.equal(beforePausedRecovery.intents[0].requestedState,'paused');assert.equal(beforePausedRecovery.runtime[0].deliveredCursor,0);await page.getByRole('button',{name:'Recover retained originals'}).click();await click('process');const stillPaused=await state();assert.equal(stillPaused.intents[0].requestedState,'paused');assert.equal(stillPaused.runtime[0].deliveredCursor,0,'Gapped runtime must not override paused delivery intent');assert.equal(stillPaused.receiptDispositions.length,0);await page.getByRole('button',{name:'Resume',exact:true}).click();await page.getByRole('button',{name:'Recover retained originals'}).click();for(let i=0;i<5;i++)await click('process');const resumed=await state();assert.equal(resumed.runtime[0].processedCursor,5);assert.equal(resumed.intents[0].requestedState,'active');assert.ok(resumed.receiptDispositions.every(r=>r.subscriptionId===resumed.intents[0].subscriptionId&&Number.isInteger(r.revision)));assert.equal((await page.locator('header nav a').allTextContents()).join('/'),'Overview/Workflows/Architecture/Data model/Subscriptions/Specification/Implementation');
  await click('reset');await sub('quotes');await click('tick');assert.match(await page.locator('#inbox').textContent(),/offline reference only/);await click('negative');assert.match(await page.locator('#inbox').textContent(),/quarantined: quote-validity/);await click('process');await click('process');await click('tick');await click('process');assert.match(await page.locator('#inbox').textContent(),/duplicate suppressed/);
  await page.locator('#consumer').selectOption('agent');assert.match(await page.locator('#consumer-help').textContent(),/checked offline/);
  await click('reset');await sub('quotes');await click('negative');await click('tick');const negativeFirst=await state();assert.equal(negativeFirst.receiptDispositions[0].disposition,'quarantined: quote-validity');assert.equal(negativeFirst.receiptDispositions[1].disposition,'awaiting review: offline reference only','Rejected input must not poison occurrence deduplication');
  await click('reset');await sub('payments');const finalStream=page.locator('.stream').filter({has:page.getByRole('heading',{name:'Payment final assertion',exact:true})});await finalStream.getByRole('button',{name:'Simulate this occurrence'}).click();assert.match(await page.locator('#inbox').textContent(),/Payment final assertion/);await page.locator('#inbox button').click();assert.match(await page.locator('#detail').textContent(),/final-payment-evidence-only/);assert.match(await page.locator('#detail').textContent(),/"executes": false/);
  assert.match(await finalStream.textContent(),/250.00 USD against 500.00 USD/);await click('process');await page.locator('.subscription select').nth(1).selectOption('payment-final');await page.getByRole('button',{name:'Save scope revision'}).click();await click('tick');assert.equal((await state()).receiptDispositions.length,1,'Final-only selector must skip pending assertion locally');await finalStream.getByRole('button',{name:'Simulate this occurrence'}).click();await click('process');const finalOnly=await state();assert.equal(finalOnly.intents[0].selector.predicate,'payment-final');assert.equal(finalOnly.runtime[0].processedCursor,3);await page.locator('#consumer').selectOption('wallet');assert.equal(await page.locator('#category').inputValue(),'quotes');await page.locator('#consumer').selectOption('dapp');assert.equal(await page.locator('#category').inputValue(),'payments');await page.locator('#consumer').selectOption('agent');assert.equal(await page.locator('#category').inputValue(),'approvals');assert.match(await page.locator('#streams').textContent(),/sandbox:reports\/demo.*5 Step.*human:alice/);await page.locator('#category').selectOption('credentials');assert.match(await page.locator('#streams').textContent(),/Credential expiry reminder/);await page.locator('#consumer').selectOption('human');assert.equal(await page.locator('#category').inputValue(),'all');
  await page.setViewportSize({width:390,height:844});await page.addStyleTag({content:'html{font-size:200%}'});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No overflow at mobile 200% text');assert.deepEqual(await page.evaluate(()=>__walletCalls),{connect:1,status:2},'Simulation must never poll or call wallet APIs automatically');assert.deepEqual(errors,[]);console.log('Subscriptions: lifecycle guards, immutable scopes, bounded replay, checkpoints, exports, fixture review/quarantine and responsive checks passed.');
 }finally{if(browser)await browser.close();await new Promise(resolve=>server.close(resolve));}
})().catch(e=>{console.error(e);process.exitCode=1;});
