'use strict';
const assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs/promises'),path=require('node:path');
let playwright;try{playwright=require('playwright');}catch{playwright=require('/home/hoskinson/.local/share/mise/installs/npm-playwright/1.63.0/node_modules/playwright');}
const dist=path.resolve(__dirname,'../dist'),out=path.resolve(__dirname,'../../reviews/subscription-workspace');
(async()=>{
 await fs.mkdir(out,{recursive:true});
 const server=http.createServer(async(req,res)=>{try{const name=decodeURIComponent(new URL(req.url,'http://localhost').pathname).slice(1),file=path.resolve(dist,name);assert.ok(file.startsWith(dist+path.sep));const body=await fs.readFile(file);res.setHeader('Content-Type',name.endsWith('.json')?'application/json':name.endsWith('.js')?'text/javascript':name.endsWith('.css')?'text/css':name.endsWith('.woff2')?'font/woff2':'text/html');res.end(body);}catch{res.statusCode=404;res.end();}});
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));let browser;
 try{
  browser=await playwright.chromium.launch({headless:true,executablePath:'/home/hoskinson/.cache/ms-playwright/chromium-1243/chrome-linux64/chrome'});
  const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),errors=[],requests=[];
  page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));
  await context.addInitScript(()=>{globalThis.__walletCalls={connect:0,status:0};globalThis.midnight={moth:{rdns:'io.shielded.moth',apiVersion:'4.0.1',connect:async networkId=>{__walletCalls.connect++;return {getConnectionStatus:async()=>{__walletCalls.status++;return {status:'connected',networkId};}};}}};});
  const url=`http://127.0.0.1:${server.address().port}/subscriptions.html`;
  await page.goto(url);await page.locator('#result-count').filter({hasText:'603 feeds'}).waitFor();
  assert.equal(await page.locator('#feeds > li').count(),50);assert.equal(await page.locator('#search').boundingBox().then(b=>b.y<1000),true);assert.deepEqual(await page.evaluate(()=>__walletCalls),{connect:0,status:0});
  const read=()=>page.evaluate(async()=>{const db=await new Promise((resolve,reject)=>{const r=indexedDB.open('midnight-express-synthetic',1);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});return new Promise(resolve=>{const tx=db.transaction(['watches','receipts','meta','folders'],'readonly'),o={};for(const key of ['watches','receipts','meta','folders']){const r=tx.objectStore(key).getAll();r.onsuccess=()=>o[key]=r.result;}tx.oncomplete=()=>{db.close();resolve(o);};});});
  const settle=async()=>{await page.waitForFunction(()=>!document.getElementById('storage-status').textContent.includes('Opening'));await page.waitForTimeout(180);};
  await page.locator('#search').fill('ops-001');await page.waitForTimeout(220); // id is deliberately outside catalog search
  await page.locator('#search').fill('urn:mpe:source:demo-ops-001');await page.locator('#result-count').filter({hasText:'1 feeds'}).waitFor();assert.equal(await page.locator('#search').evaluate(e=>document.activeElement===e),true);
  await page.locator('.feed-open').click();await settle();await page.locator('#preview-folder').waitFor();await page.locator('#preview button').filter({hasText:'Follow in demo'}).click();await settle();
  await page.locator('#organization').evaluate(e=>e.open=true);await page.locator('#folder-name').fill('Operations');await page.locator('#add-folder').click();await settle();await page.locator('#preview-folder').selectOption({label:'Operations'});await page.getByRole('button',{name:'Save scope and folder',exact:true}).click();await settle();
  assert.equal((await read()).folders[0].name,'Operations');assert.ok((await read()).watches[0].folder);
  await page.locator('[data-view=tools]').click();await settle();await page.locator('#check-simulation').click();await settle();await page.locator('#simulation').evaluate(e=>e.open=true);
  const networkBefore=requests.length;
  await page.locator('#tick').click();await settle();await page.locator('[data-view=inbox]').click();await settle();
  const before=await read();assert.equal(before.receipts.length,1);await page.getByRole('button',{name:'Mark read',exact:true}).click();await settle();assert.equal((await read()).watches[0].processed,before.watches[0].processed);
  await page.getByRole('button',{name:'Save',exact:true}).click();await settle();await page.reload();await page.locator('#storage-status').filter({hasText:'restored'}).waitFor();
  assert.deepEqual(await page.evaluate(()=>__walletCalls),{connect:0,status:0});assert.equal((await read()).receipts[0].saved,true);
  await page.getByRole('button',{name:'Record review',exact:true}).click();await page.locator('#announcement').filter({hasText:'Check the simulation'}).waitFor();assert.equal((await read()).receipts[0].disposition,'awaiting-local-review');
  await page.locator('[data-view=tools]').click();await settle();await page.locator('#check-simulation').click();await settle();await page.locator('[data-view=inbox]').click();await settle();await page.getByRole('button',{name:'Record review',exact:true}).click();await settle();assert.equal((await read()).receipts[0].disposition,'reviewed');
  await page.locator('[data-view=directory]').click();await settle();await page.locator('#clear-search').click();await settle();await page.locator('#next').click();await settle();assert.equal(await page.locator('#feeds > li').count(),50);assert.match(await page.locator('#page-range').textContent(),/51–100/);
  // Search renderer timing includes its declared 120ms settling delay and durable preference write.
  const times=[];for(const value of ['service','credential','contract','urn:mpe:source:demo-ops-010','no matching feed','']){const t=performance.now();await page.locator('#search').fill(value);const rendered=()=>page.evaluate(async v=>{const db=await new Promise(resolve=>{const r=indexedDB.open('midnight-express-synthetic',1);r.onsuccess=()=>resolve(r.result);});const saved=await new Promise(resolve=>{const r=db.transaction('meta','readonly').objectStore('meta').get('presentation');r.onsuccess=()=>resolve(r.result);});db.close();if(saved.query!==v)return false;const text=document.getElementById('result-count').textContent;return v==='service'?text.startsWith('400 '):v==='credential'?text.startsWith('200 '):v==='contract'?text.startsWith('200 '):v==='urn:mpe:source:demo-ops-010'?text.startsWith('1 '):v==='no matching feed'?text.startsWith('0 '):text.startsWith('603 ');},value);while(!await rendered()){assert.ok(performance.now()-t<5000,'Search did not settle');await page.waitForTimeout(10);}times.push(performance.now()-t);assert.ok(await page.locator('#feeds > li').count()<=50);}
  // Storage failure and CAS prevent false durable success.
  const guard=await page.evaluate(async()=>{const store=await ExpressStore.open(()=>{}),a=await store.read(),b=structuredClone(a.state);b.meta.presentation.query='uncommitted';try{await store.commit(a.state,b,a.revision,()=>{throw Error('authority changed before commit');});return 'unexpected';}catch(e){const after=await store.read();return {message:e.message,unchanged:after.revision===a.revision};}finally{store.close();}});assert.equal(guard.unchanged,true);assert.match(guard.message,/authority changed/);
  const failure=await page.evaluate(async()=>{const store=await ExpressStore.open(()=>{}),a=await store.read(),before=structuredClone(a.state),after=structuredClone(before);after.meta.presentation.query='failure';const original=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(){throw new DOMException('Injected quota failure','QuotaExceededError');};try{await store.commit(before,after,a.revision);return 'unexpected';}catch(e){return e.name+':'+e.message;}finally{IDBObjectStore.prototype.put=original;store.close();}});assert.notEqual(failure,'unexpected');
  await page.reload();await page.locator('#result-count').filter({hasText:'603'}).waitFor();
  const tab=await context.newPage();await tab.goto(url);await tab.locator('#result-count').filter({hasText:'603'}).waitFor();await tab.locator('#next').click();await tab.waitForTimeout(200);await page.locator('#storage-status').filter({hasText:'Another tab'}).waitFor();await page.locator('#manage').evaluate(e=>e.open=true);await page.locator('#reload-state').click();await settle();await tab.close();
  await page.locator('#wallet').evaluate(e=>e.open=true);await page.locator('#discover').click();assert.deepEqual(await page.evaluate(()=>__walletCalls),{connect:0,status:0});await page.locator('#wallet-ack').check();await page.locator('#connect').click();await page.locator('#wallet-status').filter({hasText:/^connected/}).waitFor();assert.deepEqual(await page.evaluate(()=>__walletCalls),{connect:1,status:1});await page.locator('#disconnect').click();
  await page.locator('#wallet').evaluate(e=>e.open=false);await page.locator('#previous').click();await settle();
  await page.locator('#search').fill('');await page.locator('#result-count').filter({hasText:'603'}).waitFor();
  await page.evaluate(async()=>{const store=await ExpressStore.open(()=>{}),a=await store.read(),b=structuredClone(a.state);b.meta.presentation.selected=null;await store.commit(a.state,b,a.revision);store.close();});await page.locator('#manage').evaluate(e=>e.open=true);await page.locator('#reload-state').click();await settle();
  const geometry=[];
  for(const [name,width,text] of [['desktop',1440,100],['mobile',390,100],['reflow',320,100],['enlarged',390,200]]){await page.setViewportSize({width,height:1000});await page.evaluate(size=>document.documentElement.style.fontSize=size+'%',text);await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));if(process.env.MPE_CAPTURE_VISUALS==='1')await page.screenshot({path:path.join(out,`${name}.png`),fullPage:false});const g=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));geometry.push({name,...g});assert.ok(g.scroll<=g.width+1,`${name} overflow: ${JSON.stringify(await page.evaluate(()=>[...document.querySelectorAll('body *')].filter(n=>n.getBoundingClientRect().right>innerWidth+1).map(n=>({tag:n.tagName,id:n.id,class:n.className,right:n.getBoundingClientRect().right})).slice(0,10)))}`);}
  await page.evaluate(()=>document.documentElement.style.fontSize='100%');await page.locator('#search').fill('urn:mpe:source:demo-ops-001');await page.locator('#result-count').filter({hasText:'1 feeds'}).waitFor();await page.locator('.feed-open').click();await settle();assert.equal(await page.locator('#catalog-pane').isVisible(),false);await page.getByRole('button',{name:'Back to results',exact:true}).click();await settle();assert.equal(await page.locator('.feed-open').evaluate(e=>document.activeElement===e),true);
  assert.equal(await page.locator('#feeds > li').count(),1);
  const cas=await page.evaluate(async()=>{const store=await ExpressStore.open(()=>{}),a=await store.read(),b=structuredClone(a.state);await store.commit(a.state,b,a.revision);try{await store.commit(a.state,b,a.revision);return 'unexpected';}catch(e){return e.message;}finally{store.close();}});assert.match(cas,/Another tab/);
  await page.reload();await page.locator('#result-count').filter({hasText:'1 feeds'}).waitFor();
  const versionchange=await page.evaluate(()=>new Promise(resolve=>{const r=indexedDB.open('midnight-express-synthetic',2);r.onsuccess=()=>{r.result.close();resolve(true);};}));assert.equal(versionchange,true);await page.locator('#storage-status').filter({hasText:'Storage changed'}).waitFor();await page.reload();await page.locator('#storage-status').filter({hasText:'unavailable'}).waitFor();
  assert.deepEqual(errors,[]);assert.ok(requests.slice(networkBefore).every(r=>r.startsWith(url.replace('subscriptions.html',''))));
  times.sort((a,b)=>a-b);await fs.writeFile(path.join(out,'browser-evidence.json'),JSON.stringify({browser:await browser.version(),platform:process.platform,viewport:geometry,settledQueryMs:times,p95:times[Math.ceil(times.length*.95)-1],errors,notes:'Local headless Chromium; query timing includes 120ms debounce, IndexedDB commit and Playwright observation. Synthetic scopes only.'},null,2));
  console.log('PASS directory, bounded pagination, search focus, follow/folders, selected receipt processing, reload authority gate, quota abort, cross-tab invalidation, explicit Moth calls and responsive preview.');
 }finally{await browser?.close();await new Promise(resolve=>server.close(resolve));}
})().catch(e=>{console.error(e);process.exitCode=1;});
