[package]
name = "mpe-client"
version.workspace = true
edition.workspace = true
[dependencies]
mpe-core = { path = "../mpe-core" }
ed25519-dalek.workspace = true
rand.workspace = true
serde.workspace = true
tokio.workspace = true
async-trait.workspace = true
[dev-dependencies]
rand_chacha.workspace = true
criterion.workspace = true

[[bench]]
name = "crypto"
harness = false

[features]
diagnostics = []
